Documentation:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/SignalException:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
AllCops:
  Exclude:
    - models/**/*
    - db/**/*
